
#include "nuitka/prelude.h"

// Sentinel PyObject to be used for all our call iterator endings. It will
// become a PyCObject pointing to NULL. It's address is unique, and that's
// enough for us to use it as sentinel value.
PyObject *_sentinel_value = NULL;

PyObject *const_int_0;
PyObject *const_str_dot;
PyObject *const_int_neg_1;
PyObject *const_int_pos_1;
PyObject *const_int_pos_2;
PyObject *const_int_pos_3;
PyObject *const_str_empty;
PyObject *const_str_space;
PyObject *const_dict_empty;
PyObject *const_str_chr_42;
PyObject *const_str_chr_43;
PyObject *const_str_chr_45;
PyObject *const_str_chr_58;
PyObject *const_str_chr_63;
PyObject *const_bytes_empty;
PyObject *const_str_chr_124;
PyObject *const_str_newline;
PyObject *const_str_plain__;
PyObject *const_str_plain_a;
PyObject *const_str_plain_c;
PyObject *const_str_plain_d;
PyObject *const_str_plain_f;
PyObject *const_str_plain_i;
PyObject *const_str_plain_j;
PyObject *const_str_plain_k;
PyObject *const_str_plain_l;
PyObject *const_str_plain_m;
PyObject *const_str_plain_n;
PyObject *const_str_plain_o;
PyObject *const_str_plain_p;
PyObject *const_str_plain_r;
PyObject *const_str_plain_s;
PyObject *const_str_plain_t;
PyObject *const_str_plain_v;
PyObject *const_str_plain_w;
PyObject *const_str_plain_x;
PyObject *const_tuple_empty;
PyObject *const_str_plain___;
PyObject *const_str_plain_os;
PyObject *const_str_plain_rb;
PyObject *const_str_plain_re;
PyObject *const_str_plain_rp;
PyObject *const_str_plain_INT;
PyObject *const_str_plain_Key;
PyObject *const_str_plain_Str;
PyObject *const_str_plain_add;
PyObject *const_str_plain_all;
PyObject *const_str_plain_any;
PyObject *const_str_plain_bfs;
PyObject *const_str_plain_cls;
PyObject *const_str_plain_cyk;
PyObject *const_str_plain_drv;
PyObject *const_str_plain_end;
PyObject *const_str_plain_get;
PyObject *const_str_plain_int;
PyObject *const_str_plain_key;
PyObject *const_str_plain_len;
PyObject *const_str_plain_lex;
PyObject *const_str_plain_map;
PyObject *const_str_plain_max;
PyObject *const_str_plain_pop;
PyObject *const_str_plain_ptr;
PyObject *const_str_plain_run;
PyObject *const_str_plain_seq;
PyObject *const_str_plain_set;
PyObject *const_str_plain_str;
PyObject *const_str_plain_sum;
PyObject *const_str_plain_sym;
PyObject *const_str_plain_sys;
PyObject *const_str_plain_zip;
PyObject *const_str_plain_BOOL;
PyObject *const_str_plain_Enum;
PyObject *const_str_plain_Item;
PyObject *const_str_plain_Lark;
PyObject *const_str_plain_None;
PyObject *const_str_plain_Py36;
PyObject *const_str_plain_REAL;
PyObject *const_str_plain_Rule;
PyObject *const_str_plain_TYPE;
PyObject *const_str_plain_Tree;
PyObject *const_str_plain_args;
PyObject *const_str_plain_auto;
PyObject *const_str_plain_bool;
PyObject *const_str_plain_call;
PyObject *const_str_plain_copy;
PyObject *const_str_plain_data;
PyObject *const_str_plain_dict;
PyObject *const_str_plain_enum;
PyObject *const_str_plain_file;
PyObject *const_str_plain_func;
PyObject *const_str_plain_item;
PyObject *const_str_plain_iter;
PyObject *const_str_plain_join;
PyObject *const_str_plain_keys;
PyObject *const_str_plain_lalr;
PyObject *const_str_plain_lark;
PyObject *const_str_plain_line;
PyObject *const_str_plain_list;
PyObject *const_str_plain_memo;
PyObject *const_str_plain_meta;
PyObject *const_str_plain_name;
PyObject *const_str_plain_next;
PyObject *const_str_plain_node;
PyObject *const_str_plain_open;
PyObject *const_str_plain_path;
PyObject *const_str_plain_pred;
PyObject *const_str_plain_read;
PyObject *const_str_plain_repr;
PyObject *const_str_plain_rule;
PyObject *const_str_plain_scan;
PyObject *const_str_plain_self;
PyObject *const_str_plain_send;
PyObject *const_str_plain_site;
PyObject *const_str_plain_term;
PyObject *const_str_plain_text;
PyObject *const_str_plain_tree;
PyObject *const_str_plain_type;
PyObject *const_str_plain_ARRAY;
PyObject *const_str_plain_DEBUG;
PyObject *const_str_plain_Debug;
PyObject *const_str_plain_FIRST;
PyObject *const_str_plain_False;
PyObject *const_str_plain_Lexer;
PyObject *const_str_plain_PyPse;
PyObject *const_str_plain_Shift;
PyObject *const_str_plain_Token;
PyObject *const_str_plain_Value;
PyObject *const_str_plain_after;
PyObject *const_str_plain_alias;
PyObject *const_str_plain_block;
PyObject *const_str_plain_bytes;
PyObject *const_str_plain_child;
PyObject *const_str_plain_close;
PyObject *const_str_plain_count;
PyObject *const_str_plain_debug;
PyObject *const_str_plain_flags;
PyObject *const_str_plain_fzset;
PyObject *const_str_plain_group;
PyObject *const_str_plain_index;
PyObject *const_str_plain_inner;
PyObject *const_str_plain_items;
PyObject *const_str_plain_label;
PyObject *const_str_plain_level;
PyObject *const_str_plain_lexer;
PyObject *const_str_plain_match;
PyObject *const_str_plain_other;
PyObject *const_str_plain_parse;
PyObject *const_str_plain_print;
PyObject *const_str_plain_range;
PyObject *const_str_plain_rules;
PyObject *const_str_plain_split;
PyObject *const_str_plain_start;
PyObject *const_str_plain_state;
PyObject *const_str_plain_throw;
PyObject *const_str_plain_token;
PyObject *const_str_plain_tuple;
PyObject *const_str_plain_type_;
PyObject *const_str_plain_types;
PyObject *const_str_plain_utils;
PyObject *const_str_plain_value;
PyObject *const_str_plain_visit;
PyObject *const_str_plain_wraps;
PyObject *const_str_angle_lambda;
PyObject *const_str_angle_string;
PyObject *const_str_plain_Column;
PyObject *const_str_plain_FOLLOW;
PyObject *const_str_plain_Parser;
PyObject *const_str_plain_STRING;
PyObject *const_str_plain_Symbol;
PyObject *const_str_plain___eq__;
PyObject *const_str_plain___ne__;
PyObject *const_str_plain__ambig;
PyObject *const_str_plain_append;
PyObject *const_str_plain_before;
PyObject *const_str_plain_blocks;
PyObject *const_str_plain_column;
PyObject *const_str_plain_common;
PyObject *const_str_plain_earley;
PyObject *const_str_plain_expect;
PyObject *const_str_plain_filter;
PyObject *const_str_plain_format;
PyObject *const_str_plain_ignore;
PyObject *const_str_plain_inline;
PyObject *const_str_plain_kwargs;
PyObject *const_str_plain_launch;
PyObject *const_str_plain_locals;
PyObject *const_str_plain_object;
PyObject *const_str_plain_origin;
PyObject *const_str_plain_output;
PyObject *const_str_plain_parser;
PyObject *const_str_plain_pretty;
PyObject *const_str_plain_regexp;
PyObject *const_str_plain_return;
PyObject *const_str_plain_rindex;
PyObject *const_str_plain_sorted;
PyObject *const_str_plain_states;
PyObject *const_str_plain_stream;
PyObject *const_str_plain_symbol;
PyObject *const_str_plain_tokens;
PyObject *const_str_plain_v_args;
PyObject *const_str_plain_value1;
PyObject *const_str_plain_value2;
PyObject *const_str_plain_values;
PyObject *const_tuple_none_tuple;
PyObject *const_tuple_true_tuple;
PyObject *const_str_angle_genexpr;
PyObject *const_str_plain_Discard;
PyObject *const_str_plain_Grammar;
PyObject *const_str_plain_Symbols;
PyObject *const_str_plain_Visitor;
PyObject *const_str_plain___all__;
PyObject *const_str_plain___cmp__;
PyObject *const_str_plain___doc__;
PyObject *const_str_plain___str__;
PyObject *const_str_plain_advance;
PyObject *const_str_plain_changed;
PyObject *const_str_plain_column0;
PyObject *const_str_plain_compare;
PyObject *const_str_plain_compile;
PyObject *const_str_plain_dirname;
PyObject *const_str_plain_dynamic;
PyObject *const_str_plain_expand1;
PyObject *const_str_plain_globals;
PyObject *const_str_plain_grammar;
PyObject *const_str_plain_initial;
PyObject *const_str_plain_inspect;
PyObject *const_str_plain_is_term;
PyObject *const_str_plain_isupper;
PyObject *const_str_plain_nonterm;
PyObject *const_str_plain_operate;
PyObject *const_str_plain_options;
PyObject *const_str_plain_partial;
PyObject *const_str_plain_pattern;
PyObject *const_str_plain_postlex;
PyObject *const_str_plain_predict;
PyObject *const_str_plain_process;
PyObject *const_str_plain_resolve;
PyObject *const_str_plain_subtree;
PyObject *const_str_plain_symbols;
PyObject *const_str_plain_to_scan;
PyObject *const_str_plain_visited;
PyObject *const_tuple_false_tuple;
PyObject *const_tuple_int_0_tuple;
PyObject *const_str_angle_listcomp;
PyObject *const_str_plain_FUNCTION;
PyObject *const_str_plain_LexError;
PyObject *const_str_plain_Operator;
PyObject *const_str_plain_Terminal;
PyObject *const_str_plain___call__;
PyObject *const_str_plain___dict__;
PyObject *const_str_plain___exit__;
PyObject *const_str_plain___file__;
PyObject *const_str_plain___hash__;
PyObject *const_str_plain___init__;
PyObject *const_str_plain___iter__;
PyObject *const_str_plain___main__;
PyObject *const_str_plain___name__;
PyObject *const_str_plain___path__;
PyObject *const_str_plain___repr__;
PyObject *const_str_plain___spec__;
PyObject *const_str_plain_analysis;
PyObject *const_str_plain_callable;
PyObject *const_str_plain_callback;
PyObject *const_str_plain_children;
PyObject *const_str_plain_classify;
PyObject *const_str_plain_compiler;
PyObject *const_str_plain_complete;
PyObject *const_str_plain_deepcopy;
PyObject *const_str_plain_end_line;
PyObject *const_str_plain_expected;
PyObject *const_str_plain_explicit;
PyObject *const_str_plain_fromlist;
PyObject *const_str_plain_get_news;
PyObject *const_str_plain_key_item;
PyObject *const_str_plain_next_set;
PyObject *const_str_plain_priority;
PyObject *const_str_plain_property;
PyObject *const_str_plain_reversed;
PyObject *const_str_plain_standard;
PyObject *const_str_plain_suppress;
PyObject *const_str_plain_terminal;
PyObject *const_str_plain_visitors;
PyObject *const_str_angle_metaclass;
PyObject *const_str_plain_ANONYMOUS;
PyObject *const_str_plain_LexerConf;
PyObject *const_str_plain_PROCEDURE;
PyObject *const_str_plain_PatternRE;
PyObject *const_str_plain_RootBlock;
PyObject *const_str_plain_TypeBlock;
PyObject *const_str_plain_ValueType;
PyObject *const_str_plain___class__;
PyObject *const_str_plain___debug__;
PyObject *const_str_plain___enter__;
PyObject *const_str_plain___slots__;
PyObject *const_str_plain_ambiguity;
PyObject *const_str_plain_bytearray;
PyObject *const_str_plain_callbacks;
PyObject *const_str_plain_end_state;
PyObject *const_str_plain_enumerate;
PyObject *const_str_plain_expansion;
PyObject *const_str_plain_find_data;
PyObject *const_str_plain_functools;
PyObject *const_str_plain_get_value;
PyObject *const_str_plain_metaclass;
PyObject *const_str_plain_new_items;
PyObject *const_str_plain_new_rules;
PyObject *const_str_plain_new_state;
PyObject *const_str_plain_operators;
PyObject *const_str_plain_param_exp;
PyObject *const_str_plain_pypse_run;
PyObject *const_str_plain_set_value;
PyObject *const_str_plain_solutions;
PyObject *const_str_plain_terminals;
PyObject *const_str_plain_to_expand;
PyObject *const_str_plain_to_reduce;
PyObject *const_str_plain_to_regexp;
PyObject *const_str_plain_transform;
PyObject *const_str_plain_valuetype;
PyObject *const_str_plain_Expression;
PyObject *const_str_plain_ParseError;
PyObject *const_str_plain_ParserConf;
PyObject *const_str_plain_PatternStr;
PyObject *const_str_plain___cached__;
PyObject *const_str_plain___import__;
PyObject *const_str_plain___loader__;
PyObject *const_str_plain___module__;
PyObject *const_str_plain_contextual;
PyObject *const_str_plain_converters;
PyObject *const_str_plain_end_column;
PyObject *const_str_plain_exceptions;
PyObject *const_str_plain_expression;
PyObject *const_str_plain_filter_out;
PyObject *const_str_plain_issubclass;
PyObject *const_str_plain_lexer_conf;
PyObject *const_str_plain_param_exps;
PyObject *const_str_plain_param_item;
PyObject *const_str_plain_param_name;
PyObject *const_str_plain_param_type;
PyObject *const_str_plain_root_block;
PyObject *const_str_plain_startswith;
PyObject *const_str_plain_to_predict;
PyObject *const_str_plain_token_tree;
PyObject *const_str_plain_tree_class;
PyObject *const_str_plain_value_type;
PyObject *const_str_plain_CUSTOM_TYPE;
PyObject *const_str_plain_DebugOutput;
PyObject *const_str_plain_NonTerminal;
PyObject *const_str_plain_OperatorAdd;
PyObject *const_str_plain_RuleOptions;
PyObject *const_str_plain_STRING_TYPE;
PyObject *const_str_plain_SlottedTree;
PyObject *const_str_plain_TerminalDef;
PyObject *const_str_plain_Transformer;
PyObject *const_str_plain___getitem__;
PyObject *const_str_plain___package__;
PyObject *const_str_plain___prepare__;
PyObject *const_str_plain_classmethod;
PyObject *const_str_plain_collections;
PyObject *const_str_plain_defaultdict;
PyObject *const_str_plain_expand_rule;
PyObject *const_str_plain_expressions;
PyObject *const_str_plain_get_context;
PyObject *const_str_plain_inline_args;
PyObject *const_str_plain_param_items;
PyObject *const_str_plain_parse_table;
PyObject *const_str_plain_parser_conf;
PyObject *const_str_plain_postprocess;
PyObject *const_str_plain_predict_all;
PyObject *const_str_plain_predictions;
PyObject *const_str_plain_scan_values;
PyObject *const_str_plain_start_state;
PyObject *const_str_plain_symbol_name;
PyObject *const_str_plain_transformer;
PyObject *const_tuple_none_none_tuple;
PyObject *const_tuple_type_list_tuple;
PyObject *const_str_plain_GrammarError;
PyObject *const_str_plain___builtins__;
PyObject *const_str_plain___deepcopy__;
PyObject *const_str_plain___internal__;
PyObject *const_str_plain___qualname__;
PyObject *const_str_plain__parse_table;
PyObject *const_str_plain_assign_value;
PyObject *const_str_plain_complete_lex;
PyObject *const_str_plain_debug_output;
PyObject *const_str_plain_get_frontend;
PyObject *const_str_plain_is_satisfied;
PyObject *const_str_plain_load_grammar;
PyObject *const_str_plain_return_value;
PyObject *const_str_plain_start_symbol;
PyObject *const_str_plain_staticmethod;
PyObject *const_str_plain_symbol_token;
PyObject *const_str_plain_term_matcher;
PyObject *const_str_plain_LALR_Analyzer;
PyObject *const_str_plain_OperatorEqual;
PyObject *const_str_plain_OperatorMinus;
PyObject *const_str_plain___metaclass__;
PyObject *const_str_plain__initializing;
PyObject *const_str_plain__pretty_label;
PyObject *const_str_plain_always_accept;
PyObject *const_str_plain_classify_bool;
PyObject *const_str_plain_current_block;
PyObject *const_str_plain_iter_subtrees;
PyObject *const_str_plain_pos_in_stream;
PyObject *const_tuple_str_plain___tuple;
PyObject *const_tuple_str_plain_c_tuple;
PyObject *const_tuple_str_plain_i_tuple;
PyObject *const_tuple_str_plain_r_tuple;
PyObject *const_tuple_str_plain_t_tuple;
PyObject *const_tuple_str_plain_x_tuple;
PyObject *const_tuple_type_object_tuple;
PyObject *const_str_angle_setcontraction;
PyObject *const_str_plain_ApplyCallbacks;
PyObject *const_str_plain_NotImplemented;
PyObject *const_str_plain_OperatorDivide;
PyObject *const_str_plain___orig_bases__;
PyObject *const_str_plain_decrease_depth;
PyObject *const_str_plain_function_block;
PyObject *const_str_plain_get_root_block;
PyObject *const_str_plain_increase_depth;
PyObject *const_str_plain_match_examples;
PyObject *const_str_plain_new_borrow_pos;
PyObject *const_str_plain_search_by_name;
PyObject *const_str_plain_user_callbacks;
PyObject *const_tuple_str_plain____tuple;
PyObject *const_tuple_str_plain_rp_tuple;
PyObject *const_slice_int_pos_1_none_none;
PyObject *const_slice_int_pos_2_none_none;
PyObject *const_slice_none_int_pos_2_none;
PyObject *const_str_angle_dictcontraction;
PyObject *const_str_plain_ContextualLexer;
PyObject *const_str_plain_GrammarAnalyzer;
PyObject *const_str_plain_UnexpectedInput;
PyObject *const_str_plain_UnexpectedToken;
PyObject *const_str_plain___mro_entries__;
PyObject *const_str_plain_create_callback;
PyObject *const_str_plain_function_params;
PyObject *const_str_plain_keep_all_tokens;
PyObject *const_str_plain_smart_decorator;
PyObject *const_str_plain_token_find_data;
PyObject *const_str_plain_value_in_python;
PyObject *const_str_plain_valuetype_token;
PyObject *const_tuple_str_plain_Key_tuple;
PyObject *const_str_plain_OperatorMultiple;
PyObject *const_str_plain_ParseTreeBuilder;
PyObject *const_str_plain_TraditionalLexer;
PyObject *const_str_plain_considered_rules;
PyObject *const_str_plain_create_decorator;
PyObject *const_str_plain_dynamic_complete;
PyObject *const_str_plain_expression_token;
PyObject *const_str_plain_get_regexp_width;
PyObject *const_str_plain_grammar_analysis;
PyObject *const_str_plain_parser_frontends;
PyObject *const_str_plain_set_parser_state;
PyObject *const_tuple_none_none_none_tuple;
PyObject *const_tuple_str_plain_Lark_tuple;
PyObject *const_tuple_str_plain_Tree_tuple;
PyObject *const_tuple_str_plain_name_tuple;
PyObject *const_tuple_str_plain_rule_tuple;
PyObject *const_tuple_str_plain_self_tuple;
PyObject *const_tuple_type_Exception_tuple;
PyObject *const_str_plain_InlineTransformer;
PyObject *const_str_plain___class_getitem__;
PyObject *const_str_plain_compute_lookahead;
PyObject *const_str_plain_output_block_attr;
PyObject *const_str_plain_resolve_ambiguity;
PyObject *const_tuple_str_plain_Token_tuple;
PyObject *const_str_plain_OperatorLargerThan;
PyObject *const_str_plain_output_block_title;
PyObject *const_str_plain_parse_tree_builder;
PyObject *const_tuple_str_plain_launch_tuple;
PyObject *const_str_plain_OperatorSmallerThan;
PyObject *const_str_plain_Transformer_InPlace;
PyObject *const_str_plain_earley__predict_all;
PyObject *const_str_plain_function_name_token;
PyObject *const_str_plain_parse_file_to_token;
PyObject *const_str_plain_propagate_positions;
PyObject *const_str_plain_register_root_block;
PyObject *const_str_plain_set_value_in_python;
PyObject *const_tuple_false_false_false_tuple;
PyObject *const_str_plain_UnexpectedCharacters;
PyObject *const_str_plain_expand_kids_by_index;
PyObject *const_str_plain_predict_and_complete;
PyObject *const_tuple_str_plain_deepcopy_tuple;
PyObject *const_tuple_str_plain_suppress_tuple;
PyObject *const_str_plain_LALR_TraditionalLexer;
PyObject *const_str_plain_array_index_exp_token;
PyObject *const_str_plain_function_params_token;
PyObject *const_tuple_str_plain___class___tuple;
PyObject *const_tuple_str_plain_pypse_run_tuple;
PyObject *const_str_plain_assign_value_in_python;
PyObject *const_str_plain_convert_token_to_value;
PyObject *const_str_plain_recursive_debug_output;
PyObject *const_str_plain_resolve__antiscore_sum;
PyObject *const_str_plain_standard_resolve_ambig;
PyObject *const_tuple_str_plain_DebugOutput_tuple;
PyObject *const_tuple_str_plain_STRING_TYPE_tuple;
PyObject *const_tuple_str_plain_defaultdict_tuple;
PyObject *const_tuple_str_plain_GrammarError_tuple;
PyObject *const_str_plain_convert_token_to_operator;
PyObject *const_str_plain_get_array_info_from_token;
PyObject *const_str_plain_convert_token_to_valuetype;
PyObject *const_str_plain_antiscore_sum_resolve_ambig;
PyObject *const_tuple_str_plain_GrammarAnalyzer_tuple;
PyObject *const_tuple_str_plain_ParseTreeBuilder_tuple;
PyObject *const_str_plain_get_symbol_name_from_key_item;
PyObject *const_tuple_str_plain_Parser_tuple_empty_tuple;
PyObject *const_tuple_str_plain_Enum_str_plain_auto_tuple;
PyObject *const_tuple_str_plain_item_str_plain_name_tuple;
PyObject *const_tuple_str_plain_self_str_plain_memo_tuple;
PyObject *const_tuple_str_plain_self_str_plain_name_tuple;
PyObject *const_tuple_str_plain_self_str_plain_text_tuple;
PyObject *const_tuple_str_plain_self_str_plain_tree_tuple;
PyObject *const_tuple_str_plain_self_str_plain_other_tuple;
PyObject *const_tuple_str_plain_self_str_plain_value_tuple;
PyObject *const_str_digest_0c7627604438feafd0b647f3dcb9a6c1;
PyObject *const_str_digest_20b42830d230d558b2406ed7a63082f7;
PyObject *const_str_digest_25731c733fd74e8333aa29126ce85686;
PyObject *const_str_digest_28b6ed448ad9c3ffe29b6a4b70688b15;
PyObject *const_str_digest_45e4dde2057b0bf276d6a84f4c917d27;
PyObject *const_str_digest_58961c73026e70b23b08cf381b49e04e;
PyObject *const_str_digest_6bfaded9b4aeab2703d0df907c36b0b3;
PyObject *const_str_digest_75fd71b1edada749c2ef7ac810062295;
PyObject *const_str_digest_77bd14080cafe517ada4eed70b1f47f4;
PyObject *const_str_digest_9816e8d1552296af90d250823c964059;
PyObject *const_str_digest_98b43dc8c0b3a0cfaa25af8d6d01d9db;
PyObject *const_str_digest_aa346f1825214b1ea81d4acc77c5877f;
PyObject *const_str_digest_ad4ac721526c18830bf8e43c9784af81;
PyObject *const_str_digest_adc474dd61fbd736d69c1bac5d9712e0;
PyObject *const_str_digest_b9c4baf879ebd882d40843df3a4dead7;
PyObject *const_str_digest_c2bf344185e4457aa9f73073f83970ab;
PyObject *const_str_digest_c74a66071bab01f59883bf86fbccc3ad;
PyObject *const_str_digest_c7e860d236633aa79696fa289b9abadb;
PyObject *const_str_digest_cf6cb6236cf4d7ba8d781b9adbcd32ea;
PyObject *const_str_digest_db35ab94a03c3cbeb13cbe2a1d728b77;
PyObject *const_str_digest_ebd73dfdaadd4df57f16b98a998b1760;
PyObject *const_str_digest_f3735b0e5a5aca57e8b9169173ded0c4;
PyObject *const_str_digest_f65e01b197ab6b5a3e5ece9ca1228291;
PyObject *const_str_digest_fdd1f239b4f3ffd6efcccf00e4a637e0;
PyObject *const_str_plain_search_symbol_by_name_recursively;
PyObject *const_tuple_68e259e8c20cde3d6b13eea8e2fad849_tuple;
PyObject *const_tuple_b7f2143cf4e19310aa212db8b6bf5b2b_tuple;
PyObject *const_str_plain_convert_param_tokens_to_param_items;
PyObject *const_str_plain_convert_symbol_token_to_symbol_name;
PyObject *const_str_plain_get_custom_type_name_from_type_token;
PyObject *const_tuple_str_plain_Symbol_str_plain_Symbols_tuple;
PyObject *const_tuple_str_plain_ValueType_str_plain_Value_tuple;
PyObject *const_tuple_str_plain_Value_str_plain_ValueType_tuple;
PyObject *const_str_plain_get_array_index_exp_token_from_key_item;
PyObject *const_tuple_str_plain_Debug_str_plain_DebugOutput_tuple;
PyObject *const_tuple_str_plain_LexerConf_str_plain_ParserConf_tuple;
PyObject *const_tuple_str_plain_i_str_plain_name_str_plain_item_tuple;
PyObject *const_tuple_str_digest_98b43dc8c0b3a0cfaa25af8d6d01d9db_tuple;
PyObject *const_tuple_anon_function_anon_builtin_function_or_method_tuple;
PyObject *const_tuple_str_plain_self_str_plain_text_str_plain_stream_tuple;
PyObject *const_tuple_str_plain_self_str_plain_before_str_plain_after_tuple;
PyObject *const_tuple_str_plain_n_str_plain_start_symbol_str_plain_column0_tuple;
PyObject *const_tuple_str_digest_b9c4baf879ebd882d40843df3a4dead7_str_plain_x_tuple;

static void _createGlobalConstants( void )
{
    NUITKA_MAY_BE_UNUSED PyObject *exception_type, *exception_value;
    NUITKA_MAY_BE_UNUSED PyTracebackObject *exception_tb;

#ifdef _MSC_VER
    // Prevent unused warnings in case of simple programs, the attribute
    // NUITKA_MAY_BE_UNUSED doesn't work for MSVC.
    (void *)exception_type; (void *)exception_value; (void *)exception_tb;
#endif

    const_int_0 = PyLong_FromUnsignedLong( 0ul );
    const_str_dot = UNSTREAM_STRING( &constant_bin[ 89 ], 1, 0 );
    const_int_neg_1 = PyLong_FromLong( -1l );
    const_int_pos_1 = PyLong_FromUnsignedLong( 1ul );
    const_int_pos_2 = PyLong_FromUnsignedLong( 2ul );
    const_int_pos_3 = PyLong_FromUnsignedLong( 3ul );
    const_str_empty = UNSTREAM_STRING( &constant_bin[ 0 ], 0, 0 );
    const_str_space = UNSTREAM_STRING( &constant_bin[ 104 ], 1, 0 );
    const_dict_empty = _PyDict_NewPresized( 0 );
    assert( PyDict_Size( const_dict_empty ) == 0 );
    const_str_chr_42 = UNSTREAM_STRING( &constant_bin[ 5798 ], 1, 0 );
    const_str_chr_43 = UNSTREAM_STRING( &constant_bin[ 4520 ], 1, 0 );
    const_str_chr_45 = UNSTREAM_STRING( &constant_bin[ 4997 ], 1, 0 );
    const_str_chr_58 = UNSTREAM_STRING( &constant_bin[ 2244 ], 1, 0 );
    const_str_chr_63 = UNSTREAM_STRING( &constant_bin[ 4526 ], 1, 0 );
    const_bytes_empty = UNSTREAM_BYTES( &constant_bin[ 0 ], 0 );
    const_str_chr_124 = UNSTREAM_STRING( &constant_bin[ 4554 ], 1, 0 );
    const_str_newline = UNSTREAM_STRING( &constant_bin[ 4502 ], 1, 0 );
    const_str_plain__ = UNSTREAM_STRING( &constant_bin[ 81 ], 1, 1 );
    const_str_plain_a = UNSTREAM_STRING( &constant_bin[ 7 ], 1, 1 );
    const_str_plain_c = UNSTREAM_STRING( &constant_bin[ 21 ], 1, 1 );
    const_str_plain_d = UNSTREAM_STRING( &constant_bin[ 100 ], 1, 1 );
    const_str_plain_f = UNSTREAM_STRING( &constant_bin[ 169 ], 1, 1 );
    const_str_plain_i = UNSTREAM_STRING( &constant_bin[ 83 ], 1, 1 );
    const_str_plain_j = UNSTREAM_STRING( &constant_bin[ 19 ], 1, 1 );
    const_str_plain_k = UNSTREAM_STRING( &constant_bin[ 9 ], 1, 1 );
    const_str_plain_l = UNSTREAM_STRING( &constant_bin[ 11 ], 1, 1 );
    const_str_plain_m = UNSTREAM_STRING( &constant_bin[ 3 ], 1, 1 );
    const_str_plain_n = UNSTREAM_STRING( &constant_bin[ 8 ], 1, 1 );
    const_str_plain_o = UNSTREAM_STRING( &constant_bin[ 2 ], 1, 1 );
    const_str_plain_p = UNSTREAM_STRING( &constant_bin[ 90 ], 1, 1 );
    const_str_plain_r = UNSTREAM_STRING( &constant_bin[ 17 ], 1, 1 );
    const_str_plain_s = UNSTREAM_STRING( &constant_bin[ 23 ], 1, 1 );
    const_str_plain_t = UNSTREAM_STRING( &constant_bin[ 22 ], 1, 1 );
    const_str_plain_v = UNSTREAM_STRING( &constant_bin[ 118 ], 1, 1 );
    const_str_plain_w = UNSTREAM_STRING( &constant_bin[ 146 ], 1, 1 );
    const_str_plain_x = UNSTREAM_STRING( &constant_bin[ 180 ], 1, 1 );
    const_tuple_empty = PyTuple_New( 0 );
    const_str_plain___ = UNSTREAM_STRING( &constant_bin[ 81 ], 2, 1 );
    const_str_plain_os = UNSTREAM_STRING( &constant_bin[ 8891 ], 2, 1 );
    const_str_plain_rb = UNSTREAM_STRING( &constant_bin[ 11273 ], 2, 1 );
    const_str_plain_re = UNSTREAM_STRING( &constant_bin[ 111 ], 2, 1 );
    const_str_plain_rp = UNSTREAM_STRING( &constant_bin[ 9927 ], 2, 1 );
    const_str_plain_INT = UNSTREAM_STRING( &constant_bin[ 7110 ], 3, 1 );
    const_str_plain_Key = UNSTREAM_STRING( &constant_bin[ 3693 ], 3, 1 );
    const_str_plain_Str = UNSTREAM_STRING( &constant_bin[ 2260 ], 3, 1 );
    const_str_plain_add = UNSTREAM_STRING( &constant_bin[ 2483 ], 3, 1 );
    const_str_plain_all = UNSTREAM_STRING( &constant_bin[ 415 ], 3, 1 );
    const_str_plain_any = UNSTREAM_STRING( &constant_bin[ 13477 ], 3, 1 );
    const_str_plain_bfs = UNSTREAM_STRING( &constant_bin[ 32101 ], 3, 1 );
    const_str_plain_cls = UNSTREAM_STRING( &constant_bin[ 22026 ], 3, 1 );
    const_str_plain_cyk = UNSTREAM_STRING( &constant_bin[ 22901 ], 3, 1 );
    const_str_plain_drv = UNSTREAM_STRING( &constant_bin[ 25136 ], 3, 1 );
    const_str_plain_end = UNSTREAM_STRING( &constant_bin[ 186 ], 3, 1 );
    const_str_plain_get = UNSTREAM_STRING( &constant_bin[ 2598 ], 3, 1 );
    const_str_plain_int = UNSTREAM_STRING( &constant_bin[ 2749 ], 3, 1 );
    const_str_plain_key = UNSTREAM_STRING( &constant_bin[ 1274 ], 3, 1 );
    const_str_plain_len = UNSTREAM_STRING( &constant_bin[ 10060 ], 3, 1 );
    const_str_plain_lex = UNSTREAM_STRING( &constant_bin[ 8893 ], 3, 1 );
    const_str_plain_map = UNSTREAM_STRING( &constant_bin[ 9161 ], 3, 1 );
    const_str_plain_max = UNSTREAM_STRING( &constant_bin[ 13128 ], 3, 1 );
    const_str_plain_pop = UNSTREAM_STRING( &constant_bin[ 29581 ], 3, 1 );
    const_str_plain_ptr = UNSTREAM_STRING( &constant_bin[ 25820 ], 3, 1 );
    const_str_plain_run = UNSTREAM_STRING( &constant_bin[ 236 ], 3, 1 );
    const_str_plain_seq = UNSTREAM_STRING( &constant_bin[ 32104 ], 3, 1 );
    const_str_plain_set = UNSTREAM_STRING( &constant_bin[ 3281 ], 3, 1 );
    const_str_plain_str = UNSTREAM_STRING( &constant_bin[ 2410 ], 3, 1 );
    const_str_plain_sum = UNSTREAM_STRING( &constant_bin[ 8009 ], 3, 1 );
    const_str_plain_sym = UNSTREAM_STRING( &constant_bin[ 1048 ], 3, 1 );
    const_str_plain_sys = UNSTREAM_STRING( &constant_bin[ 32107 ], 3, 1 );
    const_str_plain_zip = UNSTREAM_STRING( &constant_bin[ 32110 ], 3, 1 );
    const_str_plain_BOOL = UNSTREAM_STRING( &constant_bin[ 7179 ], 4, 1 );
    const_str_plain_Enum = UNSTREAM_STRING( &constant_bin[ 32113 ], 4, 1 );
    const_str_plain_Item = UNSTREAM_STRING( &constant_bin[ 3276 ], 4, 1 );
    const_str_plain_Lark = UNSTREAM_STRING( &constant_bin[ 8909 ], 4, 1 );
    const_str_plain_None = UNSTREAM_STRING( &constant_bin[ 11503 ], 4, 1 );
    const_str_plain_Py36 = UNSTREAM_STRING( &constant_bin[ 32117 ], 4, 1 );
    const_str_plain_REAL = UNSTREAM_STRING( &constant_bin[ 7131 ], 4, 1 );
    const_str_plain_Rule = UNSTREAM_STRING( &constant_bin[ 9411 ], 4, 1 );
    const_str_plain_TYPE = UNSTREAM_STRING( &constant_bin[ 4943 ], 4, 1 );
    const_str_plain_Tree = UNSTREAM_STRING( &constant_bin[ 17163 ], 4, 1 );
    const_str_plain_args = UNSTREAM_STRING( &constant_bin[ 16444 ], 4, 1 );
    const_str_plain_auto = UNSTREAM_STRING( &constant_bin[ 10736 ], 4, 1 );
    const_str_plain_bool = UNSTREAM_STRING( &constant_bin[ 2554 ], 4, 1 );
    const_str_plain_call = UNSTREAM_STRING( &constant_bin[ 414 ], 4, 1 );
    const_str_plain_copy = UNSTREAM_STRING( &constant_bin[ 13286 ], 4, 1 );
    const_str_plain_data = UNSTREAM_STRING( &constant_bin[ 24253 ], 4, 1 );
    const_str_plain_dict = UNSTREAM_STRING( &constant_bin[ 9150 ], 4, 1 );
    const_str_plain_enum = UNSTREAM_STRING( &constant_bin[ 32121 ], 4, 1 );
    const_str_plain_file = UNSTREAM_STRING( &constant_bin[ 4422 ], 4, 1 );
    const_str_plain_func = UNSTREAM_STRING( &constant_bin[ 260 ], 4, 1 );
    const_str_plain_item = UNSTREAM_STRING( &constant_bin[ 3451 ], 4, 1 );
    const_str_plain_iter = UNSTREAM_STRING( &constant_bin[ 14903 ], 4, 1 );
    const_str_plain_join = UNSTREAM_STRING( &constant_bin[ 18506 ], 4, 1 );
    const_str_plain_keys = UNSTREAM_STRING( &constant_bin[ 3712 ], 4, 1 );
    const_str_plain_lalr = UNSTREAM_STRING( &constant_bin[ 9901 ], 4, 1 );
    const_str_plain_lark = UNSTREAM_STRING( &constant_bin[ 8470 ], 4, 1 );
    const_str_plain_line = UNSTREAM_STRING( &constant_bin[ 8730 ], 4, 1 );
    const_str_plain_list = UNSTREAM_STRING( &constant_bin[ 8098 ], 4, 1 );
    const_str_plain_memo = UNSTREAM_STRING( &constant_bin[ 32125 ], 4, 1 );
    const_str_plain_meta = UNSTREAM_STRING( &constant_bin[ 28113 ], 4, 1 );
    const_str_plain_name = UNSTREAM_STRING( &constant_bin[ 290 ], 4, 1 );
    const_str_plain_next = UNSTREAM_STRING( &constant_bin[ 25796 ], 4, 1 );
    const_str_plain_node = UNSTREAM_STRING( &constant_bin[ 11157 ], 4, 1 );
    const_str_plain_open = UNSTREAM_STRING( &constant_bin[ 11963 ], 4, 1 );
    const_str_plain_path = UNSTREAM_STRING( &constant_bin[ 7813 ], 4, 1 );
    const_str_plain_pred = UNSTREAM_STRING( &constant_bin[ 24857 ], 4, 1 );
    const_str_plain_read = UNSTREAM_STRING( &constant_bin[ 21692 ], 4, 1 );
    const_str_plain_repr = UNSTREAM_STRING( &constant_bin[ 8209 ], 4, 1 );
    const_str_plain_rule = UNSTREAM_STRING( &constant_bin[ 11062 ], 4, 1 );
    const_str_plain_scan = UNSTREAM_STRING( &constant_bin[ 8789 ], 4, 1 );
    const_str_plain_self = UNSTREAM_STRING( &constant_bin[ 14453 ], 4, 1 );
    const_str_plain_send = UNSTREAM_STRING( &constant_bin[ 32129 ], 4, 1 );
    const_str_plain_site = UNSTREAM_STRING( &constant_bin[ 8456 ], 4, 1 );
    const_str_plain_term = UNSTREAM_STRING( &constant_bin[ 8843 ], 4, 1 );
    const_str_plain_text = UNSTREAM_STRING( &constant_bin[ 4427 ], 4, 1 );
    const_str_plain_tree = UNSTREAM_STRING( &constant_bin[ 9860 ], 4, 1 );
    const_str_plain_type = UNSTREAM_STRING( &constant_bin[ 201 ], 4, 1 );
    const_str_plain_ARRAY = UNSTREAM_STRING( &constant_bin[ 7202 ], 5, 1 );
    const_str_plain_DEBUG = UNSTREAM_STRING( &constant_bin[ 4873 ], 5, 1 );
    const_str_plain_Debug = UNSTREAM_STRING( &constant_bin[ 1389 ], 5, 1 );
    const_str_plain_FIRST = UNSTREAM_STRING( &constant_bin[ 32133 ], 5, 1 );
    const_str_plain_False = UNSTREAM_STRING( &constant_bin[ 11291 ], 5, 1 );
    const_str_plain_Lexer = UNSTREAM_STRING( &constant_bin[ 8674 ], 5, 1 );
    const_str_plain_PyPse = UNSTREAM_STRING( &constant_bin[ 25 ], 5, 1 );
    const_str_plain_Shift = UNSTREAM_STRING( &constant_bin[ 26833 ], 5, 1 );
    const_str_plain_Token = UNSTREAM_STRING( &constant_bin[ 2238 ], 5, 1 );
    const_str_plain_Value = UNSTREAM_STRING( &constant_bin[ 8166 ], 5, 1 );
    const_str_plain_after = UNSTREAM_STRING( &constant_bin[ 32138 ], 5, 1 );
    const_str_plain_alias = UNSTREAM_STRING( &constant_bin[ 15070 ], 5, 1 );
    const_str_plain_block = UNSTREAM_STRING( &constant_bin[ 139 ], 5, 1 );
    const_str_plain_bytes = UNSTREAM_STRING( &constant_bin[ 32143 ], 5, 1 );
    const_str_plain_child = UNSTREAM_STRING( &constant_bin[ 134 ], 5, 1 );
    const_str_plain_close = UNSTREAM_STRING( &constant_bin[ 18902 ], 5, 1 );
    const_str_plain_count = UNSTREAM_STRING( &constant_bin[ 25043 ], 5, 1 );
    const_str_plain_debug = UNSTREAM_STRING( &constant_bin[ 121 ], 5, 1 );
    const_str_plain_flags = UNSTREAM_STRING( &constant_bin[ 13196 ], 5, 1 );
    const_str_plain_fzset = UNSTREAM_STRING( &constant_bin[ 29208 ], 5, 1 );
    const_str_plain_group = UNSTREAM_STRING( &constant_bin[ 13775 ], 5, 1 );
    const_str_plain_index = UNSTREAM_STRING( &constant_bin[ 1428 ], 5, 1 );
    const_str_plain_inner = UNSTREAM_STRING( &constant_bin[ 30373 ], 5, 1 );
    const_str_plain_items = UNSTREAM_STRING( &constant_bin[ 3688 ], 5, 1 );
    const_str_plain_label = UNSTREAM_STRING( &constant_bin[ 9174 ], 5, 1 );
    const_str_plain_level = UNSTREAM_STRING( &constant_bin[ 32148 ], 5, 1 );
    const_str_plain_lexer = UNSTREAM_STRING( &constant_bin[ 9962 ], 5, 1 );
    const_str_plain_match = UNSTREAM_STRING( &constant_bin[ 9291 ], 5, 1 );
    const_str_plain_other = UNSTREAM_STRING( &constant_bin[ 13076 ], 5, 1 );
    const_str_plain_parse = UNSTREAM_STRING( &constant_bin[ 4472 ], 5, 1 );
    const_str_plain_print = UNSTREAM_STRING( &constant_bin[ 3000 ], 5, 1 );
    const_str_plain_range = UNSTREAM_STRING( &constant_bin[ 16090 ], 5, 1 );
    const_str_plain_rules = UNSTREAM_STRING( &constant_bin[ 11062 ], 5, 1 );
    const_str_plain_split = UNSTREAM_STRING( &constant_bin[ 9090 ], 5, 1 );
    const_str_plain_start = UNSTREAM_STRING( &constant_bin[ 173 ], 5, 1 );
    const_str_plain_state = UNSTREAM_STRING( &constant_bin[ 13621 ], 5, 1 );
    const_str_plain_throw = UNSTREAM_STRING( &constant_bin[ 32153 ], 5, 1 );
    const_str_plain_token = UNSTREAM_STRING( &constant_bin[ 183 ], 5, 1 );
    const_str_plain_tuple = UNSTREAM_STRING( &constant_bin[ 32158 ], 5, 1 );
    const_str_plain_type_ = UNSTREAM_STRING( &constant_bin[ 492 ], 5, 1 );
    const_str_plain_types = UNSTREAM_STRING( &constant_bin[ 13571 ], 5, 1 );
    const_str_plain_utils = UNSTREAM_STRING( &constant_bin[ 29188 ], 5, 1 );
    const_str_plain_value = UNSTREAM_STRING( &constant_bin[ 245 ], 5, 1 );
    const_str_plain_visit = UNSTREAM_STRING( &constant_bin[ 29933 ], 5, 1 );
    const_str_plain_wraps = UNSTREAM_STRING( &constant_bin[ 32163 ], 5, 1 );
    const_str_angle_lambda = UNSTREAM_STRING( &constant_bin[ 13692 ], 8, 0 );
    const_str_angle_string = UNSTREAM_STRING( &constant_bin[ 32168 ], 8, 0 );
    const_str_plain_Column = UNSTREAM_STRING( &constant_bin[ 25007 ], 6, 1 );
    const_str_plain_FOLLOW = UNSTREAM_STRING( &constant_bin[ 25856 ], 6, 1 );
    const_str_plain_Parser = UNSTREAM_STRING( &constant_bin[ 8590 ], 6, 1 );
    const_str_plain_STRING = UNSTREAM_STRING( &constant_bin[ 7155 ], 6, 1 );
    const_str_plain_Symbol = UNSTREAM_STRING( &constant_bin[ 7971 ], 6, 1 );
    const_str_plain___eq__ = UNSTREAM_STRING( &constant_bin[ 9488 ], 6, 1 );
    const_str_plain___ne__ = UNSTREAM_STRING( &constant_bin[ 9524 ], 6, 1 );
    const_str_plain__ambig = UNSTREAM_STRING( &constant_bin[ 11144 ], 6, 1 );
    const_str_plain_append = UNSTREAM_STRING( &constant_bin[ 8085 ], 6, 1 );
    const_str_plain_before = UNSTREAM_STRING( &constant_bin[ 32176 ], 6, 1 );
    const_str_plain_blocks = UNSTREAM_STRING( &constant_bin[ 139 ], 6, 1 );
    const_str_plain_column = UNSTREAM_STRING( &constant_bin[ 8739 ], 6, 1 );
    const_str_plain_common = UNSTREAM_STRING( &constant_bin[ 7524 ], 6, 1 );
    const_str_plain_earley = UNSTREAM_STRING( &constant_bin[ 10224 ], 6, 1 );
    const_str_plain_expect = UNSTREAM_STRING( &constant_bin[ 8709 ], 6, 1 );
    const_str_plain_filter = UNSTREAM_STRING( &constant_bin[ 21091 ], 6, 1 );
    const_str_plain_format = UNSTREAM_STRING( &constant_bin[ 24056 ], 6, 1 );
    const_str_plain_ignore = UNSTREAM_STRING( &constant_bin[ 7735 ], 6, 1 );
    const_str_plain_inline = UNSTREAM_STRING( &constant_bin[ 21061 ], 6, 1 );
    const_str_plain_kwargs = UNSTREAM_STRING( &constant_bin[ 32182 ], 6, 1 );
    const_str_plain_launch = UNSTREAM_STRING( &constant_bin[ 32188 ], 6, 1 );
    const_str_plain_locals = UNSTREAM_STRING( &constant_bin[ 1987 ], 6, 1 );
    const_str_plain_object = UNSTREAM_STRING( &constant_bin[ 12820 ], 6, 1 );
    const_str_plain_origin = UNSTREAM_STRING( &constant_bin[ 9539 ], 6, 1 );
    const_str_plain_output = UNSTREAM_STRING( &constant_bin[ 127 ], 6, 1 );
    const_str_plain_parser = UNSTREAM_STRING( &constant_bin[ 4472 ], 6, 1 );
    const_str_plain_pretty = UNSTREAM_STRING( &constant_bin[ 25495 ], 6, 1 );
    const_str_plain_regexp = UNSTREAM_STRING( &constant_bin[ 13405 ], 6, 1 );
    const_str_plain_return = UNSTREAM_STRING( &constant_bin[ 485 ], 6, 1 );
    const_str_plain_rindex = UNSTREAM_STRING( &constant_bin[ 32194 ], 6, 1 );
    const_str_plain_sorted = UNSTREAM_STRING( &constant_bin[ 32200 ], 6, 1 );
    const_str_plain_states = UNSTREAM_STRING( &constant_bin[ 26721 ], 6, 1 );
    const_str_plain_stream = UNSTREAM_STRING( &constant_bin[ 14459 ], 6, 1 );
    const_str_plain_symbol = UNSTREAM_STRING( &constant_bin[ 1048 ], 6, 1 );
    const_str_plain_tokens = UNSTREAM_STRING( &constant_bin[ 1060 ], 6, 1 );
    const_str_plain_v_args = UNSTREAM_STRING( &constant_bin[ 31637 ], 6, 1 );
    const_str_plain_value1 = UNSTREAM_STRING( &constant_bin[ 32206 ], 6, 1 );
    const_str_plain_value2 = UNSTREAM_STRING( &constant_bin[ 32212 ], 6, 1 );
    const_str_plain_values = UNSTREAM_STRING( &constant_bin[ 8195 ], 6, 1 );
    const_tuple_none_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_none_tuple, 0, Py_None ); Py_INCREF( Py_None );
    const_tuple_true_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_true_tuple, 0, Py_True ); Py_INCREF( Py_True );
    const_str_angle_genexpr = UNSTREAM_STRING( &constant_bin[ 13172 ], 9, 0 );
    const_str_plain_Discard = UNSTREAM_STRING( &constant_bin[ 32218 ], 7, 1 );
    const_str_plain_Grammar = UNSTREAM_STRING( &constant_bin[ 14911 ], 7, 1 );
    const_str_plain_Symbols = UNSTREAM_STRING( &constant_bin[ 7971 ], 7, 1 );
    const_str_plain_Visitor = UNSTREAM_STRING( &constant_bin[ 17765 ], 7, 1 );
    const_str_plain___all__ = UNSTREAM_STRING( &constant_bin[ 32225 ], 7, 1 );
    const_str_plain___cmp__ = UNSTREAM_STRING( &constant_bin[ 32232 ], 7, 1 );
    const_str_plain___doc__ = UNSTREAM_STRING( &constant_bin[ 32239 ], 7, 1 );
    const_str_plain___str__ = UNSTREAM_STRING( &constant_bin[ 23541 ], 7, 1 );
    const_str_plain_advance = UNSTREAM_STRING( &constant_bin[ 25766 ], 7, 1 );
    const_str_plain_changed = UNSTREAM_STRING( &constant_bin[ 32246 ], 7, 1 );
    const_str_plain_column0 = UNSTREAM_STRING( &constant_bin[ 32253 ], 7, 1 );
    const_str_plain_compare = UNSTREAM_STRING( &constant_bin[ 27460 ], 7, 1 );
    const_str_plain_compile = UNSTREAM_STRING( &constant_bin[ 2312 ], 7, 1 );
    const_str_plain_dirname = UNSTREAM_STRING( &constant_bin[ 32260 ], 7, 1 );
    const_str_plain_dynamic = UNSTREAM_STRING( &constant_bin[ 10502 ], 7, 1 );
    const_str_plain_expand1 = UNSTREAM_STRING( &constant_bin[ 32267 ], 7, 1 );
    const_str_plain_globals = UNSTREAM_STRING( &constant_bin[ 32274 ], 7, 1 );
    const_str_plain_grammar = UNSTREAM_STRING( &constant_bin[ 9403 ], 7, 1 );
    const_str_plain_initial = UNSTREAM_STRING( &constant_bin[ 32281 ], 7, 1 );
    const_str_plain_inspect = UNSTREAM_STRING( &constant_bin[ 32288 ], 7, 1 );
    const_str_plain_is_term = UNSTREAM_STRING( &constant_bin[ 32295 ], 7, 1 );
    const_str_plain_isupper = UNSTREAM_STRING( &constant_bin[ 32302 ], 7, 1 );
    const_str_plain_nonterm = UNSTREAM_STRING( &constant_bin[ 16068 ], 7, 1 );
    const_str_plain_operate = UNSTREAM_STRING( &constant_bin[ 3928 ], 7, 1 );
    const_str_plain_options = UNSTREAM_STRING( &constant_bin[ 10123 ], 7, 1 );
    const_str_plain_partial = UNSTREAM_STRING( &constant_bin[ 32309 ], 7, 1 );
    const_str_plain_pattern = UNSTREAM_STRING( &constant_bin[ 17092 ], 7, 1 );
    const_str_plain_postlex = UNSTREAM_STRING( &constant_bin[ 11461 ], 7, 1 );
    const_str_plain_predict = UNSTREAM_STRING( &constant_bin[ 24857 ], 7, 1 );
    const_str_plain_process = UNSTREAM_STRING( &constant_bin[ 11482 ], 7, 1 );
    const_str_plain_resolve = UNSTREAM_STRING( &constant_bin[ 10908 ], 7, 1 );
    const_str_plain_subtree = UNSTREAM_STRING( &constant_bin[ 22685 ], 7, 1 );
    const_str_plain_symbols = UNSTREAM_STRING( &constant_bin[ 2067 ], 7, 1 );
    const_str_plain_to_scan = UNSTREAM_STRING( &constant_bin[ 32316 ], 7, 1 );
    const_str_plain_visited = UNSTREAM_STRING( &constant_bin[ 32323 ], 7, 1 );
    const_tuple_false_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_false_tuple, 0, Py_False ); Py_INCREF( Py_False );
    const_tuple_int_0_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_0_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    const_str_angle_listcomp = UNSTREAM_STRING( &constant_bin[ 32330 ], 10, 0 );
    const_str_plain_FUNCTION = UNSTREAM_STRING( &constant_bin[ 5549 ], 8, 1 );
    const_str_plain_LexError = UNSTREAM_STRING( &constant_bin[ 32340 ], 8, 1 );
    const_str_plain_Operator = UNSTREAM_STRING( &constant_bin[ 3919 ], 8, 1 );
    const_str_plain_Terminal = UNSTREAM_STRING( &constant_bin[ 9373 ], 8, 1 );
    const_str_plain___call__ = UNSTREAM_STRING( &constant_bin[ 13800 ], 8, 1 );
    const_str_plain___dict__ = UNSTREAM_STRING( &constant_bin[ 32348 ], 8, 1 );
    const_str_plain___exit__ = UNSTREAM_STRING( &constant_bin[ 32356 ], 8, 1 );
    const_str_plain___file__ = UNSTREAM_STRING( &constant_bin[ 12350 ], 8, 1 );
    const_str_plain___hash__ = UNSTREAM_STRING( &constant_bin[ 9438 ], 8, 1 );
    const_str_plain___init__ = UNSTREAM_STRING( &constant_bin[ 81 ], 8, 1 );
    const_str_plain___iter__ = UNSTREAM_STRING( &constant_bin[ 32364 ], 8, 1 );
    const_str_plain___main__ = UNSTREAM_STRING( &constant_bin[ 32372 ], 8, 1 );
    const_str_plain___name__ = UNSTREAM_STRING( &constant_bin[ 32380 ], 8, 1 );
    const_str_plain___path__ = UNSTREAM_STRING( &constant_bin[ 32388 ], 8, 1 );
    const_str_plain___repr__ = UNSTREAM_STRING( &constant_bin[ 8207 ], 8, 1 );
    const_str_plain___spec__ = UNSTREAM_STRING( &constant_bin[ 32396 ], 8, 1 );
    const_str_plain_analysis = UNSTREAM_STRING( &constant_bin[ 22416 ], 8, 1 );
    const_str_plain_callable = UNSTREAM_STRING( &constant_bin[ 32404 ], 8, 1 );
    const_str_plain_callback = UNSTREAM_STRING( &constant_bin[ 11845 ], 8, 1 );
    const_str_plain_children = UNSTREAM_STRING( &constant_bin[ 28095 ], 8, 1 );
    const_str_plain_classify = UNSTREAM_STRING( &constant_bin[ 32412 ], 8, 1 );
    const_str_plain_compiler = UNSTREAM_STRING( &constant_bin[ 2312 ], 8, 1 );
    const_str_plain_complete = UNSTREAM_STRING( &constant_bin[ 10583 ], 8, 1 );
    const_str_plain_deepcopy = UNSTREAM_STRING( &constant_bin[ 13282 ], 8, 1 );
    const_str_plain_end_line = UNSTREAM_STRING( &constant_bin[ 11774 ], 8, 1 );
    const_str_plain_expected = UNSTREAM_STRING( &constant_bin[ 8709 ], 8, 1 );
    const_str_plain_explicit = UNSTREAM_STRING( &constant_bin[ 11082 ], 8, 1 );
    const_str_plain_fromlist = UNSTREAM_STRING( &constant_bin[ 32420 ], 8, 1 );
    const_str_plain_get_news = UNSTREAM_STRING( &constant_bin[ 25619 ], 8, 1 );
    const_str_plain_key_item = UNSTREAM_STRING( &constant_bin[ 3684 ], 8, 1 );
    const_str_plain_next_set = UNSTREAM_STRING( &constant_bin[ 32428 ], 8, 1 );
    const_str_plain_priority = UNSTREAM_STRING( &constant_bin[ 3151 ], 8, 1 );
    const_str_plain_property = UNSTREAM_STRING( &constant_bin[ 32436 ], 8, 1 );
    const_str_plain_reversed = UNSTREAM_STRING( &constant_bin[ 32444 ], 8, 1 );
    const_str_plain_standard = UNSTREAM_STRING( &constant_bin[ 10384 ], 8, 1 );
    const_str_plain_suppress = UNSTREAM_STRING( &constant_bin[ 29336 ], 8, 1 );
    const_str_plain_terminal = UNSTREAM_STRING( &constant_bin[ 8843 ], 8, 1 );
    const_str_plain_visitors = UNSTREAM_STRING( &constant_bin[ 30667 ], 8, 1 );
    const_str_angle_metaclass = UNSTREAM_STRING( &constant_bin[ 32452 ], 11, 0 );
    const_str_plain_ANONYMOUS = UNSTREAM_STRING( &constant_bin[ 32463 ], 9, 1 );
    const_str_plain_LexerConf = UNSTREAM_STRING( &constant_bin[ 8674 ], 9, 1 );
    const_str_plain_PROCEDURE = UNSTREAM_STRING( &constant_bin[ 5654 ], 9, 1 );
    const_str_plain_PatternRE = UNSTREAM_STRING( &constant_bin[ 13118 ], 9, 1 );
    const_str_plain_RootBlock = UNSTREAM_STRING( &constant_bin[ 1350 ], 9, 1 );
    const_str_plain_TypeBlock = UNSTREAM_STRING( &constant_bin[ 1081 ], 9, 1 );
    const_str_plain_ValueType = UNSTREAM_STRING( &constant_bin[ 32472 ], 9, 1 );
    const_str_plain___class__ = UNSTREAM_STRING( &constant_bin[ 32481 ], 9, 1 );
    const_str_plain___debug__ = UNSTREAM_STRING( &constant_bin[ 32490 ], 9, 1 );
    const_str_plain___enter__ = UNSTREAM_STRING( &constant_bin[ 32499 ], 9, 1 );
    const_str_plain___slots__ = UNSTREAM_STRING( &constant_bin[ 32508 ], 9, 1 );
    const_str_plain_ambiguity = UNSTREAM_STRING( &constant_bin[ 10804 ], 9, 1 );
    const_str_plain_bytearray = UNSTREAM_STRING( &constant_bin[ 32517 ], 9, 1 );
    const_str_plain_callbacks = UNSTREAM_STRING( &constant_bin[ 11845 ], 9, 1 );
    const_str_plain_end_state = UNSTREAM_STRING( &constant_bin[ 26777 ], 9, 1 );
    const_str_plain_enumerate = UNSTREAM_STRING( &constant_bin[ 32526 ], 9, 1 );
    const_str_plain_expansion = UNSTREAM_STRING( &constant_bin[ 9565 ], 9, 1 );
    const_str_plain_find_data = UNSTREAM_STRING( &constant_bin[ 28634 ], 9, 1 );
    const_str_plain_functools = UNSTREAM_STRING( &constant_bin[ 32535 ], 9, 1 );
    const_str_plain_get_value = UNSTREAM_STRING( &constant_bin[ 2598 ], 9, 1 );
    const_str_plain_metaclass = UNSTREAM_STRING( &constant_bin[ 32453 ], 9, 1 );
    const_str_plain_new_items = UNSTREAM_STRING( &constant_bin[ 32544 ], 9, 1 );
    const_str_plain_new_rules = UNSTREAM_STRING( &constant_bin[ 32553 ], 9, 1 );
    const_str_plain_new_state = UNSTREAM_STRING( &constant_bin[ 32562 ], 9, 1 );
    const_str_plain_operators = UNSTREAM_STRING( &constant_bin[ 4012 ], 9, 1 );
    const_str_plain_param_exp = UNSTREAM_STRING( &constant_bin[ 32571 ], 9, 1 );
    const_str_plain_pypse_run = UNSTREAM_STRING( &constant_bin[ 32580 ], 9, 1 );
    const_str_plain_set_value = UNSTREAM_STRING( &constant_bin[ 3281 ], 9, 1 );
    const_str_plain_solutions = UNSTREAM_STRING( &constant_bin[ 32589 ], 9, 1 );
    const_str_plain_terminals = UNSTREAM_STRING( &constant_bin[ 14382 ], 9, 1 );
    const_str_plain_to_expand = UNSTREAM_STRING( &constant_bin[ 32598 ], 9, 1 );
    const_str_plain_to_reduce = UNSTREAM_STRING( &constant_bin[ 32607 ], 9, 1 );
    const_str_plain_to_regexp = UNSTREAM_STRING( &constant_bin[ 14186 ], 9, 1 );
    const_str_plain_transform = UNSTREAM_STRING( &constant_bin[ 9765 ], 9, 1 );
    const_str_plain_valuetype = UNSTREAM_STRING( &constant_bin[ 753 ], 9, 1 );
    const_str_plain_Expression = UNSTREAM_STRING( &constant_bin[ 3381 ], 10, 1 );
    const_str_plain_ParseError = UNSTREAM_STRING( &constant_bin[ 32616 ], 10, 1 );
    const_str_plain_ParserConf = UNSTREAM_STRING( &constant_bin[ 8590 ], 10, 1 );
    const_str_plain_PatternStr = UNSTREAM_STRING( &constant_bin[ 13755 ], 10, 1 );
    const_str_plain___cached__ = UNSTREAM_STRING( &constant_bin[ 32626 ], 10, 1 );
    const_str_plain___import__ = UNSTREAM_STRING( &constant_bin[ 32636 ], 10, 1 );
    const_str_plain___loader__ = UNSTREAM_STRING( &constant_bin[ 32646 ], 10, 1 );
    const_str_plain___module__ = UNSTREAM_STRING( &constant_bin[ 32656 ], 10, 1 );
    const_str_plain_contextual = UNSTREAM_STRING( &constant_bin[ 10429 ], 10, 1 );
    const_str_plain_converters = UNSTREAM_STRING( &constant_bin[ 2397 ], 10, 1 );
    const_str_plain_end_column = UNSTREAM_STRING( &constant_bin[ 11784 ], 10, 1 );
    const_str_plain_exceptions = UNSTREAM_STRING( &constant_bin[ 8697 ], 10, 1 );
    const_str_plain_expression = UNSTREAM_STRING( &constant_bin[ 630 ], 10, 1 );
    const_str_plain_filter_out = UNSTREAM_STRING( &constant_bin[ 32666 ], 10, 1 );
    const_str_plain_issubclass = UNSTREAM_STRING( &constant_bin[ 32676 ], 10, 1 );
    const_str_plain_lexer_conf = UNSTREAM_STRING( &constant_bin[ 32686 ], 10, 1 );
    const_str_plain_param_exps = UNSTREAM_STRING( &constant_bin[ 32696 ], 10, 1 );
    const_str_plain_param_item = UNSTREAM_STRING( &constant_bin[ 32706 ], 10, 1 );
    const_str_plain_param_name = UNSTREAM_STRING( &constant_bin[ 32716 ], 10, 1 );
    const_str_plain_param_type = UNSTREAM_STRING( &constant_bin[ 32726 ], 10, 1 );
    const_str_plain_root_block = UNSTREAM_STRING( &constant_bin[ 2876 ], 10, 1 );
    const_str_plain_startswith = UNSTREAM_STRING( &constant_bin[ 32736 ], 10, 1 );
    const_str_plain_to_predict = UNSTREAM_STRING( &constant_bin[ 32746 ], 10, 1 );
    const_str_plain_token_tree = UNSTREAM_STRING( &constant_bin[ 32756 ], 10, 1 );
    const_str_plain_tree_class = UNSTREAM_STRING( &constant_bin[ 32766 ], 10, 1 );
    const_str_plain_value_type = UNSTREAM_STRING( &constant_bin[ 32776 ], 10, 1 );
    const_str_plain_CUSTOM_TYPE = UNSTREAM_STRING( &constant_bin[ 32786 ], 11, 1 );
    const_str_plain_DebugOutput = UNSTREAM_STRING( &constant_bin[ 2911 ], 11, 1 );
    const_str_plain_NonTerminal = UNSTREAM_STRING( &constant_bin[ 32797 ], 11, 1 );
    const_str_plain_OperatorAdd = UNSTREAM_STRING( &constant_bin[ 4129 ], 11, 1 );
    const_str_plain_RuleOptions = UNSTREAM_STRING( &constant_bin[ 9446 ], 11, 1 );
    const_str_plain_STRING_TYPE = UNSTREAM_STRING( &constant_bin[ 32808 ], 11, 1 );
    const_str_plain_SlottedTree = UNSTREAM_STRING( &constant_bin[ 32819 ], 11, 1 );
    const_str_plain_TerminalDef = UNSTREAM_STRING( &constant_bin[ 13254 ], 11, 1 );
    const_str_plain_Transformer = UNSTREAM_STRING( &constant_bin[ 30091 ], 11, 1 );
    const_str_plain___getitem__ = UNSTREAM_STRING( &constant_bin[ 32830 ], 11, 1 );
    const_str_plain___package__ = UNSTREAM_STRING( &constant_bin[ 32841 ], 11, 1 );
    const_str_plain___prepare__ = UNSTREAM_STRING( &constant_bin[ 32852 ], 11, 1 );
    const_str_plain_classmethod = UNSTREAM_STRING( &constant_bin[ 32863 ], 11, 1 );
    const_str_plain_collections = UNSTREAM_STRING( &constant_bin[ 32874 ], 11, 1 );
    const_str_plain_defaultdict = UNSTREAM_STRING( &constant_bin[ 32885 ], 11, 1 );
    const_str_plain_expand_rule = UNSTREAM_STRING( &constant_bin[ 25951 ], 11, 1 );
    const_str_plain_expressions = UNSTREAM_STRING( &constant_bin[ 3189 ], 11, 1 );
    const_str_plain_get_context = UNSTREAM_STRING( &constant_bin[ 9018 ], 11, 1 );
    const_str_plain_inline_args = UNSTREAM_STRING( &constant_bin[ 21061 ], 11, 1 );
    const_str_plain_param_items = UNSTREAM_STRING( &constant_bin[ 32896 ], 11, 1 );
    const_str_plain_parse_table = UNSTREAM_STRING( &constant_bin[ 32907 ], 11, 1 );
    const_str_plain_parser_conf = UNSTREAM_STRING( &constant_bin[ 32918 ], 11, 1 );
    const_str_plain_postprocess = UNSTREAM_STRING( &constant_bin[ 21953 ], 11, 1 );
    const_str_plain_predict_all = UNSTREAM_STRING( &constant_bin[ 32929 ], 11, 1 );
    const_str_plain_predictions = UNSTREAM_STRING( &constant_bin[ 32940 ], 11, 1 );
    const_str_plain_scan_values = UNSTREAM_STRING( &constant_bin[ 28877 ], 11, 1 );
    const_str_plain_start_state = UNSTREAM_STRING( &constant_bin[ 32951 ], 11, 1 );
    const_str_plain_symbol_name = UNSTREAM_STRING( &constant_bin[ 32962 ], 11, 1 );
    const_str_plain_transformer = UNSTREAM_STRING( &constant_bin[ 9765 ], 11, 1 );
    const_tuple_none_none_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_none_none_tuple, 0, Py_None ); Py_INCREF( Py_None );
    PyTuple_SET_ITEM( const_tuple_none_none_tuple, 1, Py_None ); Py_INCREF( Py_None );
    const_tuple_type_list_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_type_list_tuple, 0, (PyObject *)&PyList_Type ); Py_INCREF( (PyObject *)&PyList_Type );
    const_str_plain_GrammarError = UNSTREAM_STRING( &constant_bin[ 32973 ], 12, 1 );
    const_str_plain___builtins__ = UNSTREAM_STRING( &constant_bin[ 32985 ], 12, 1 );
    const_str_plain___deepcopy__ = UNSTREAM_STRING( &constant_bin[ 13280 ], 12, 1 );
    const_str_plain___internal__ = UNSTREAM_STRING( &constant_bin[ 32997 ], 12, 1 );
    const_str_plain___qualname__ = UNSTREAM_STRING( &constant_bin[ 33009 ], 12, 1 );
    const_str_plain__parse_table = UNSTREAM_STRING( &constant_bin[ 33021 ], 12, 1 );
    const_str_plain_assign_value = UNSTREAM_STRING( &constant_bin[ 8310 ], 12, 1 );
    const_str_plain_complete_lex = UNSTREAM_STRING( &constant_bin[ 33033 ], 12, 1 );
    const_str_plain_debug_output = UNSTREAM_STRING( &constant_bin[ 121 ], 12, 1 );
    const_str_plain_get_frontend = UNSTREAM_STRING( &constant_bin[ 33045 ], 12, 1 );
    const_str_plain_is_satisfied = UNSTREAM_STRING( &constant_bin[ 26116 ], 12, 1 );
    const_str_plain_load_grammar = UNSTREAM_STRING( &constant_bin[ 14944 ], 12, 1 );
    const_str_plain_return_value = UNSTREAM_STRING( &constant_bin[ 33057 ], 12, 1 );
    const_str_plain_start_symbol = UNSTREAM_STRING( &constant_bin[ 33069 ], 12, 1 );
    const_str_plain_staticmethod = UNSTREAM_STRING( &constant_bin[ 33081 ], 12, 1 );
    const_str_plain_symbol_token = UNSTREAM_STRING( &constant_bin[ 33093 ], 12, 1 );
    const_str_plain_term_matcher = UNSTREAM_STRING( &constant_bin[ 33105 ], 12, 1 );
    const_str_plain_LALR_Analyzer = UNSTREAM_STRING( &constant_bin[ 26658 ], 13, 1 );
    const_str_plain_OperatorEqual = UNSTREAM_STRING( &constant_bin[ 4074 ], 13, 1 );
    const_str_plain_OperatorMinus = UNSTREAM_STRING( &constant_bin[ 3984 ], 13, 1 );
    const_str_plain___metaclass__ = UNSTREAM_STRING( &constant_bin[ 33117 ], 13, 1 );
    const_str_plain__initializing = UNSTREAM_STRING( &constant_bin[ 33130 ], 13, 1 );
    const_str_plain__pretty_label = UNSTREAM_STRING( &constant_bin[ 25494 ], 13, 1 );
    const_str_plain_always_accept = UNSTREAM_STRING( &constant_bin[ 33143 ], 13, 1 );
    const_str_plain_classify_bool = UNSTREAM_STRING( &constant_bin[ 33156 ], 13, 1 );
    const_str_plain_current_block = UNSTREAM_STRING( &constant_bin[ 33169 ], 13, 1 );
    const_str_plain_iter_subtrees = UNSTREAM_STRING( &constant_bin[ 28586 ], 13, 1 );
    const_str_plain_pos_in_stream = UNSTREAM_STRING( &constant_bin[ 33182 ], 13, 1 );
    const_tuple_str_plain___tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain___tuple, 0, const_str_plain__ ); Py_INCREF( const_str_plain__ );
    const_tuple_str_plain_c_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_c_tuple, 0, const_str_plain_c ); Py_INCREF( const_str_plain_c );
    const_tuple_str_plain_i_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_i_tuple, 0, const_str_plain_i ); Py_INCREF( const_str_plain_i );
    const_tuple_str_plain_r_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_r_tuple, 0, const_str_plain_r ); Py_INCREF( const_str_plain_r );
    const_tuple_str_plain_t_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_t_tuple, 0, const_str_plain_t ); Py_INCREF( const_str_plain_t );
    const_tuple_str_plain_x_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_x_tuple, 0, const_str_plain_x ); Py_INCREF( const_str_plain_x );
    const_tuple_type_object_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_type_object_tuple, 0, (PyObject *)&PyBaseObject_Type ); Py_INCREF( (PyObject *)&PyBaseObject_Type );
    const_str_angle_setcontraction = UNSTREAM_STRING( &constant_bin[ 33195 ], 16, 0 );
    const_str_plain_ApplyCallbacks = UNSTREAM_STRING( &constant_bin[ 24874 ], 14, 1 );
    const_str_plain_NotImplemented = UNSTREAM_STRING( &constant_bin[ 33211 ], 14, 1 );
    const_str_plain_OperatorDivide = UNSTREAM_STRING( &constant_bin[ 4206 ], 14, 1 );
    const_str_plain___orig_bases__ = UNSTREAM_STRING( &constant_bin[ 33225 ], 14, 1 );
    const_str_plain_decrease_depth = UNSTREAM_STRING( &constant_bin[ 3079 ], 14, 1 );
    const_str_plain_function_block = UNSTREAM_STRING( &constant_bin[ 260 ], 14, 1 );
    const_str_plain_get_root_block = UNSTREAM_STRING( &constant_bin[ 2872 ], 14, 1 );
    const_str_plain_increase_depth = UNSTREAM_STRING( &constant_bin[ 2923 ], 14, 1 );
    const_str_plain_match_examples = UNSTREAM_STRING( &constant_bin[ 9359 ], 14, 1 );
    const_str_plain_new_borrow_pos = UNSTREAM_STRING( &constant_bin[ 14029 ], 14, 1 );
    const_str_plain_search_by_name = UNSTREAM_STRING( &constant_bin[ 8043 ], 14, 1 );
    const_str_plain_user_callbacks = UNSTREAM_STRING( &constant_bin[ 33239 ], 14, 1 );
    const_tuple_str_plain____tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain____tuple, 0, const_str_plain___ ); Py_INCREF( const_str_plain___ );
    const_tuple_str_plain_rp_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_rp_tuple, 0, const_str_plain_rp ); Py_INCREF( const_str_plain_rp );
    const_slice_int_pos_1_none_none = PySlice_New( const_int_pos_1, Py_None, Py_None );
    const_slice_int_pos_2_none_none = PySlice_New( const_int_pos_2, Py_None, Py_None );
    const_slice_none_int_pos_2_none = PySlice_New( Py_None, const_int_pos_2, Py_None );
    const_str_angle_dictcontraction = UNSTREAM_STRING( &constant_bin[ 33253 ], 17, 0 );
    const_str_plain_ContextualLexer = UNSTREAM_STRING( &constant_bin[ 13723 ], 15, 1 );
    const_str_plain_GrammarAnalyzer = UNSTREAM_STRING( &constant_bin[ 26021 ], 15, 1 );
    const_str_plain_UnexpectedInput = UNSTREAM_STRING( &constant_bin[ 9002 ], 15, 1 );
    const_str_plain_UnexpectedToken = UNSTREAM_STRING( &constant_bin[ 9095 ], 15, 1 );
    const_str_plain___mro_entries__ = UNSTREAM_STRING( &constant_bin[ 33270 ], 15, 1 );
    const_str_plain_create_callback = UNSTREAM_STRING( &constant_bin[ 21419 ], 15, 1 );
    const_str_plain_function_params = UNSTREAM_STRING( &constant_bin[ 5923 ], 15, 1 );
    const_str_plain_keep_all_tokens = UNSTREAM_STRING( &constant_bin[ 11306 ], 15, 1 );
    const_str_plain_smart_decorator = UNSTREAM_STRING( &constant_bin[ 33285 ], 15, 1 );
    const_str_plain_token_find_data = UNSTREAM_STRING( &constant_bin[ 33300 ], 15, 1 );
    const_str_plain_value_in_python = UNSTREAM_STRING( &constant_bin[ 245 ], 15, 1 );
    const_str_plain_valuetype_token = UNSTREAM_STRING( &constant_bin[ 33315 ], 15, 1 );
    const_tuple_str_plain_Key_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Key_tuple, 0, const_str_plain_Key ); Py_INCREF( const_str_plain_Key );
    const_str_plain_OperatorMultiple = UNSTREAM_STRING( &constant_bin[ 4100 ], 16, 1 );
    const_str_plain_ParseTreeBuilder = UNSTREAM_STRING( &constant_bin[ 21402 ], 16, 1 );
    const_str_plain_TraditionalLexer = UNSTREAM_STRING( &constant_bin[ 13137 ], 16, 1 );
    const_str_plain_considered_rules = UNSTREAM_STRING( &constant_bin[ 33330 ], 16, 1 );
    const_str_plain_create_decorator = UNSTREAM_STRING( &constant_bin[ 29627 ], 16, 1 );
    const_str_plain_dynamic_complete = UNSTREAM_STRING( &constant_bin[ 10575 ], 16, 1 );
    const_str_plain_expression_token = UNSTREAM_STRING( &constant_bin[ 630 ], 16, 1 );
    const_str_plain_get_regexp_width = UNSTREAM_STRING( &constant_bin[ 33346 ], 16, 1 );
    const_str_plain_grammar_analysis = UNSTREAM_STRING( &constant_bin[ 22408 ], 16, 1 );
    const_str_plain_parser_frontends = UNSTREAM_STRING( &constant_bin[ 21925 ], 16, 1 );
    const_str_plain_set_parser_state = UNSTREAM_STRING( &constant_bin[ 13739 ], 16, 1 );
    const_tuple_none_none_none_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_none_none_none_tuple, 0, Py_None ); Py_INCREF( Py_None );
    PyTuple_SET_ITEM( const_tuple_none_none_none_tuple, 1, Py_None ); Py_INCREF( Py_None );
    PyTuple_SET_ITEM( const_tuple_none_none_none_tuple, 2, Py_None ); Py_INCREF( Py_None );
    const_tuple_str_plain_Lark_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Lark_tuple, 0, const_str_plain_Lark ); Py_INCREF( const_str_plain_Lark );
    const_tuple_str_plain_Tree_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Tree_tuple, 0, const_str_plain_Tree ); Py_INCREF( const_str_plain_Tree );
    const_tuple_str_plain_name_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_name_tuple, 0, const_str_plain_name ); Py_INCREF( const_str_plain_name );
    const_tuple_str_plain_rule_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_rule_tuple, 0, const_str_plain_rule ); Py_INCREF( const_str_plain_rule );
    const_tuple_str_plain_self_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    const_tuple_type_Exception_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_type_Exception_tuple, 0, (PyObject *)PyExc_Exception ); Py_INCREF( (PyObject *)PyExc_Exception );
    const_str_plain_InlineTransformer = UNSTREAM_STRING( &constant_bin[ 32045 ], 17, 1 );
    const_str_plain___class_getitem__ = UNSTREAM_STRING( &constant_bin[ 33362 ], 17, 1 );
    const_str_plain_compute_lookahead = UNSTREAM_STRING( &constant_bin[ 26672 ], 17, 1 );
    const_str_plain_output_block_attr = UNSTREAM_STRING( &constant_bin[ 2949 ], 17, 1 );
    const_str_plain_resolve_ambiguity = UNSTREAM_STRING( &constant_bin[ 33379 ], 17, 1 );
    const_tuple_str_plain_Token_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Token_tuple, 0, const_str_plain_Token ); Py_INCREF( const_str_plain_Token );
    const_str_plain_OperatorLargerThan = UNSTREAM_STRING( &constant_bin[ 3935 ], 18, 1 );
    const_str_plain_output_block_title = UNSTREAM_STRING( &constant_bin[ 3033 ], 18, 1 );
    const_str_plain_parse_tree_builder = UNSTREAM_STRING( &constant_bin[ 13100 ], 18, 1 );
    const_tuple_str_plain_launch_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_launch_tuple, 0, const_str_plain_launch ); Py_INCREF( const_str_plain_launch );
    const_str_plain_OperatorSmallerThan = UNSTREAM_STRING( &constant_bin[ 4174 ], 19, 1 );
    const_str_plain_Transformer_InPlace = UNSTREAM_STRING( &constant_bin[ 30308 ], 19, 1 );
    const_str_plain_earley__predict_all = UNSTREAM_STRING( &constant_bin[ 33396 ], 19, 1 );
    const_str_plain_function_name_token = UNSTREAM_STRING( &constant_bin[ 33415 ], 19, 1 );
    const_str_plain_parse_file_to_token = UNSTREAM_STRING( &constant_bin[ 33434 ], 19, 1 );
    const_str_plain_propagate_positions = UNSTREAM_STRING( &constant_bin[ 11726 ], 19, 1 );
    const_str_plain_register_root_block = UNSTREAM_STRING( &constant_bin[ 2892 ], 19, 1 );
    const_str_plain_set_value_in_python = UNSTREAM_STRING( &constant_bin[ 3852 ], 19, 1 );
    const_tuple_false_false_false_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_false_false_false_tuple, 0, Py_False ); Py_INCREF( Py_False );
    PyTuple_SET_ITEM( const_tuple_false_false_false_tuple, 1, Py_False ); Py_INCREF( Py_False );
    PyTuple_SET_ITEM( const_tuple_false_false_false_tuple, 2, Py_False ); Py_INCREF( Py_False );
    const_str_plain_UnexpectedCharacters = UNSTREAM_STRING( &constant_bin[ 9029 ], 20, 1 );
    const_str_plain_expand_kids_by_index = UNSTREAM_STRING( &constant_bin[ 28435 ], 20, 1 );
    const_str_plain_predict_and_complete = UNSTREAM_STRING( &constant_bin[ 33453 ], 20, 1 );
    const_tuple_str_plain_deepcopy_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_deepcopy_tuple, 0, const_str_plain_deepcopy ); Py_INCREF( const_str_plain_deepcopy );
    const_tuple_str_plain_suppress_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_suppress_tuple, 0, const_str_plain_suppress ); Py_INCREF( const_str_plain_suppress );
    const_str_plain_LALR_TraditionalLexer = UNSTREAM_STRING( &constant_bin[ 22360 ], 21, 1 );
    const_str_plain_array_index_exp_token = UNSTREAM_STRING( &constant_bin[ 33473 ], 21, 1 );
    const_str_plain_function_params_token = UNSTREAM_STRING( &constant_bin[ 33494 ], 21, 1 );
    const_tuple_str_plain___class___tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain___class___tuple, 0, const_str_plain___class__ ); Py_INCREF( const_str_plain___class__ );
    const_tuple_str_plain_pypse_run_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_pypse_run_tuple, 0, const_str_plain_pypse_run ); Py_INCREF( const_str_plain_pypse_run );
    const_str_plain_assign_value_in_python = UNSTREAM_STRING( &constant_bin[ 8310 ], 22, 1 );
    const_str_plain_convert_token_to_value = UNSTREAM_STRING( &constant_bin[ 33515 ], 22, 1 );
    const_str_plain_recursive_debug_output = UNSTREAM_STRING( &constant_bin[ 111 ], 22, 1 );
    const_str_plain_resolve__antiscore_sum = UNSTREAM_STRING( &constant_bin[ 33537 ], 22, 1 );
    const_str_plain_standard_resolve_ambig = UNSTREAM_STRING( &constant_bin[ 27625 ], 22, 1 );
    const_tuple_str_plain_DebugOutput_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_DebugOutput_tuple, 0, const_str_plain_DebugOutput ); Py_INCREF( const_str_plain_DebugOutput );
    const_tuple_str_plain_STRING_TYPE_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_STRING_TYPE_tuple, 0, const_str_plain_STRING_TYPE ); Py_INCREF( const_str_plain_STRING_TYPE );
    const_tuple_str_plain_defaultdict_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_defaultdict_tuple, 0, const_str_plain_defaultdict ); Py_INCREF( const_str_plain_defaultdict );
    const_tuple_str_plain_GrammarError_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_GrammarError_tuple, 0, const_str_plain_GrammarError ); Py_INCREF( const_str_plain_GrammarError );
    const_str_plain_convert_token_to_operator = UNSTREAM_STRING( &constant_bin[ 33559 ], 25, 1 );
    const_str_plain_get_array_info_from_token = UNSTREAM_STRING( &constant_bin[ 33584 ], 25, 1 );
    const_str_plain_convert_token_to_valuetype = UNSTREAM_STRING( &constant_bin[ 33609 ], 26, 1 );
    const_str_plain_antiscore_sum_resolve_ambig = UNSTREAM_STRING( &constant_bin[ 27510 ], 27, 1 );
    const_tuple_str_plain_GrammarAnalyzer_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_GrammarAnalyzer_tuple, 0, const_str_plain_GrammarAnalyzer ); Py_INCREF( const_str_plain_GrammarAnalyzer );
    const_tuple_str_plain_ParseTreeBuilder_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_ParseTreeBuilder_tuple, 0, const_str_plain_ParseTreeBuilder ); Py_INCREF( const_str_plain_ParseTreeBuilder );
    const_str_plain_get_symbol_name_from_key_item = UNSTREAM_STRING( &constant_bin[ 33635 ], 29, 1 );
    const_tuple_str_plain_Parser_tuple_empty_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Parser_tuple_empty_tuple, 0, const_str_plain_Parser ); Py_INCREF( const_str_plain_Parser );
    PyTuple_SET_ITEM( const_tuple_str_plain_Parser_tuple_empty_tuple, 1, const_tuple_empty ); Py_INCREF( const_tuple_empty );
    const_tuple_str_plain_Enum_str_plain_auto_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Enum_str_plain_auto_tuple, 0, const_str_plain_Enum ); Py_INCREF( const_str_plain_Enum );
    PyTuple_SET_ITEM( const_tuple_str_plain_Enum_str_plain_auto_tuple, 1, const_str_plain_auto ); Py_INCREF( const_str_plain_auto );
    const_tuple_str_plain_item_str_plain_name_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_item_str_plain_name_tuple, 0, const_str_plain_item ); Py_INCREF( const_str_plain_item );
    PyTuple_SET_ITEM( const_tuple_str_plain_item_str_plain_name_tuple, 1, const_str_plain_name ); Py_INCREF( const_str_plain_name );
    const_tuple_str_plain_self_str_plain_memo_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_memo_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_memo_tuple, 1, const_str_plain_memo ); Py_INCREF( const_str_plain_memo );
    const_tuple_str_plain_self_str_plain_name_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_name_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_name_tuple, 1, const_str_plain_name ); Py_INCREF( const_str_plain_name );
    const_tuple_str_plain_self_str_plain_text_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_text_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_text_tuple, 1, const_str_plain_text ); Py_INCREF( const_str_plain_text );
    const_tuple_str_plain_self_str_plain_tree_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_tree_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_tree_tuple, 1, const_str_plain_tree ); Py_INCREF( const_str_plain_tree );
    const_tuple_str_plain_self_str_plain_other_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_other_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_other_tuple, 1, const_str_plain_other ); Py_INCREF( const_str_plain_other );
    const_tuple_str_plain_self_str_plain_value_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_value_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_value_tuple, 1, const_str_plain_value ); Py_INCREF( const_str_plain_value );
    const_str_digest_0c7627604438feafd0b647f3dcb9a6c1 = UNSTREAM_STRING( &constant_bin[ 33664 ], 16, 0 );
    const_str_digest_20b42830d230d558b2406ed7a63082f7 = UNSTREAM_STRING( &constant_bin[ 33680 ], 29, 0 );
    const_str_digest_25731c733fd74e8333aa29126ce85686 = UNSTREAM_STRING( &constant_bin[ 19313 ], 2, 0 );
    const_str_digest_28b6ed448ad9c3ffe29b6a4b70688b15 = UNSTREAM_STRING( &constant_bin[ 24295 ], 13, 0 );
    const_str_digest_45e4dde2057b0bf276d6a84f4c917d27 = UNSTREAM_STRING( &constant_bin[ 15152 ], 7, 0 );
    const_str_digest_58961c73026e70b23b08cf381b49e04e = UNSTREAM_STRING( &constant_bin[ 33709 ], 15, 0 );
    const_str_digest_6bfaded9b4aeab2703d0df907c36b0b3 = UNSTREAM_STRING( &constant_bin[ 33724 ], 30, 0 );
    const_str_digest_75fd71b1edada749c2ef7ac810062295 = UNSTREAM_STRING( &constant_bin[ 33754 ], 46, 0 );
    const_str_digest_77bd14080cafe517ada4eed70b1f47f4 = UNSTREAM_STRING( &constant_bin[ 27174 ], 15, 0 );
    const_str_digest_9816e8d1552296af90d250823c964059 = UNSTREAM_STRING( &constant_bin[ 33800 ], 46, 0 );
    const_str_digest_98b43dc8c0b3a0cfaa25af8d6d01d9db = UNSTREAM_STRING( &constant_bin[ 33846 ], 4, 0 );
    const_str_digest_aa346f1825214b1ea81d4acc77c5877f = UNSTREAM_STRING( &constant_bin[ 33850 ], 13, 0 );
    const_str_digest_ad4ac721526c18830bf8e43c9784af81 = UNSTREAM_STRING( &constant_bin[ 33863 ], 38, 0 );
    const_str_digest_adc474dd61fbd736d69c1bac5d9712e0 = UNSTREAM_STRING( &constant_bin[ 33901 ], 47, 0 );
    const_str_digest_b9c4baf879ebd882d40843df3a4dead7 = UNSTREAM_STRING( &constant_bin[ 33948 ], 2, 1 );
    const_str_digest_c2bf344185e4457aa9f73073f83970ab = UNSTREAM_STRING( &constant_bin[ 33950 ], 15, 0 );
    const_str_digest_c74a66071bab01f59883bf86fbccc3ad = UNSTREAM_STRING( &constant_bin[ 23536 ], 12, 0 );
    const_str_digest_c7e860d236633aa79696fa289b9abadb = UNSTREAM_STRING( &constant_bin[ 33965 ], 42, 0 );
    const_str_digest_cf6cb6236cf4d7ba8d781b9adbcd32ea = UNSTREAM_STRING( &constant_bin[ 34007 ], 10, 0 );
    const_str_digest_db35ab94a03c3cbeb13cbe2a1d728b77 = UNSTREAM_STRING( &constant_bin[ 8180 ], 2, 0 );
    const_str_digest_ebd73dfdaadd4df57f16b98a998b1760 = UNSTREAM_STRING( &constant_bin[ 24337 ], 12, 0 );
    const_str_digest_f3735b0e5a5aca57e8b9169173ded0c4 = UNSTREAM_STRING( &constant_bin[ 25048 ], 26, 0 );
    const_str_digest_f65e01b197ab6b5a3e5ece9ca1228291 = UNSTREAM_STRING( &constant_bin[ 34017 ], 13, 0 );
    const_str_digest_fdd1f239b4f3ffd6efcccf00e4a637e0 = UNSTREAM_STRING( &constant_bin[ 34030 ], 48, 0 );
    const_str_plain_search_symbol_by_name_recursively = UNSTREAM_STRING( &constant_bin[ 1118 ], 33, 1 );
    const_tuple_68e259e8c20cde3d6b13eea8e2fad849_tuple = PyTuple_New( 8 );
    PyTuple_SET_ITEM( const_tuple_68e259e8c20cde3d6b13eea8e2fad849_tuple, 0, const_str_plain_column ); Py_INCREF( const_str_plain_column );
    PyTuple_SET_ITEM( const_tuple_68e259e8c20cde3d6b13eea8e2fad849_tuple, 1, const_str_plain_to_predict ); Py_INCREF( const_str_plain_to_predict );
    PyTuple_SET_ITEM( const_tuple_68e259e8c20cde3d6b13eea8e2fad849_tuple, 2, const_str_plain_to_reduce ); Py_INCREF( const_str_plain_to_reduce );
    PyTuple_SET_ITEM( const_tuple_68e259e8c20cde3d6b13eea8e2fad849_tuple, 3, const_str_plain_nonterm ); Py_INCREF( const_str_plain_nonterm );
    PyTuple_SET_ITEM( const_tuple_68e259e8c20cde3d6b13eea8e2fad849_tuple, 4, const_str_plain_item ); Py_INCREF( const_str_plain_item );
    PyTuple_SET_ITEM( const_tuple_68e259e8c20cde3d6b13eea8e2fad849_tuple, 5, const_str_plain_new_items ); Py_INCREF( const_str_plain_new_items );
    PyTuple_SET_ITEM( const_tuple_68e259e8c20cde3d6b13eea8e2fad849_tuple, 6, const_str_plain_predict ); Py_INCREF( const_str_plain_predict );
    PyTuple_SET_ITEM( const_tuple_68e259e8c20cde3d6b13eea8e2fad849_tuple, 7, const_str_plain_complete ); Py_INCREF( const_str_plain_complete );
    const_tuple_b7f2143cf4e19310aa212db8b6bf5b2b_tuple = PyTuple_New( 4 );
    PyTuple_SET_ITEM( const_tuple_b7f2143cf4e19310aa212db8b6bf5b2b_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_b7f2143cf4e19310aa212db8b6bf5b2b_tuple, 1, const_str_plain_data ); Py_INCREF( const_str_plain_data );
    PyTuple_SET_ITEM( const_tuple_b7f2143cf4e19310aa212db8b6bf5b2b_tuple, 2, const_str_plain_children ); Py_INCREF( const_str_plain_children );
    PyTuple_SET_ITEM( const_tuple_b7f2143cf4e19310aa212db8b6bf5b2b_tuple, 3, const_str_plain_meta ); Py_INCREF( const_str_plain_meta );
    const_str_plain_convert_param_tokens_to_param_items = UNSTREAM_STRING( &constant_bin[ 34078 ], 35, 1 );
    const_str_plain_convert_symbol_token_to_symbol_name = UNSTREAM_STRING( &constant_bin[ 34113 ], 35, 1 );
    const_str_plain_get_custom_type_name_from_type_token = UNSTREAM_STRING( &constant_bin[ 34148 ], 36, 1 );
    const_tuple_str_plain_Symbol_str_plain_Symbols_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Symbol_str_plain_Symbols_tuple, 0, const_str_plain_Symbol ); Py_INCREF( const_str_plain_Symbol );
    PyTuple_SET_ITEM( const_tuple_str_plain_Symbol_str_plain_Symbols_tuple, 1, const_str_plain_Symbols ); Py_INCREF( const_str_plain_Symbols );
    const_tuple_str_plain_ValueType_str_plain_Value_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_ValueType_str_plain_Value_tuple, 0, const_str_plain_ValueType ); Py_INCREF( const_str_plain_ValueType );
    PyTuple_SET_ITEM( const_tuple_str_plain_ValueType_str_plain_Value_tuple, 1, const_str_plain_Value ); Py_INCREF( const_str_plain_Value );
    const_tuple_str_plain_Value_str_plain_ValueType_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Value_str_plain_ValueType_tuple, 0, const_str_plain_Value ); Py_INCREF( const_str_plain_Value );
    PyTuple_SET_ITEM( const_tuple_str_plain_Value_str_plain_ValueType_tuple, 1, const_str_plain_ValueType ); Py_INCREF( const_str_plain_ValueType );
    const_str_plain_get_array_index_exp_token_from_key_item = UNSTREAM_STRING( &constant_bin[ 34184 ], 39, 1 );
    const_tuple_str_plain_Debug_str_plain_DebugOutput_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Debug_str_plain_DebugOutput_tuple, 0, const_str_plain_Debug ); Py_INCREF( const_str_plain_Debug );
    PyTuple_SET_ITEM( const_tuple_str_plain_Debug_str_plain_DebugOutput_tuple, 1, const_str_plain_DebugOutput ); Py_INCREF( const_str_plain_DebugOutput );
    const_tuple_str_plain_LexerConf_str_plain_ParserConf_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_LexerConf_str_plain_ParserConf_tuple, 0, const_str_plain_LexerConf ); Py_INCREF( const_str_plain_LexerConf );
    PyTuple_SET_ITEM( const_tuple_str_plain_LexerConf_str_plain_ParserConf_tuple, 1, const_str_plain_ParserConf ); Py_INCREF( const_str_plain_ParserConf );
    const_tuple_str_plain_i_str_plain_name_str_plain_item_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_str_plain_i_str_plain_name_str_plain_item_tuple, 0, const_str_plain_i ); Py_INCREF( const_str_plain_i );
    PyTuple_SET_ITEM( const_tuple_str_plain_i_str_plain_name_str_plain_item_tuple, 1, const_str_plain_name ); Py_INCREF( const_str_plain_name );
    PyTuple_SET_ITEM( const_tuple_str_plain_i_str_plain_name_str_plain_item_tuple, 2, const_str_plain_item ); Py_INCREF( const_str_plain_item );
    const_tuple_str_digest_98b43dc8c0b3a0cfaa25af8d6d01d9db_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_digest_98b43dc8c0b3a0cfaa25af8d6d01d9db_tuple, 0, const_str_digest_98b43dc8c0b3a0cfaa25af8d6d01d9db ); Py_INCREF( const_str_digest_98b43dc8c0b3a0cfaa25af8d6d01d9db );
    const_tuple_anon_function_anon_builtin_function_or_method_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_anon_function_anon_builtin_function_or_method_tuple, 0, (PyObject *)&PyFunction_Type ); Py_INCREF( (PyObject *)&PyFunction_Type );
    PyTuple_SET_ITEM( const_tuple_anon_function_anon_builtin_function_or_method_tuple, 1, (PyObject *)&PyCFunction_Type ); Py_INCREF( (PyObject *)&PyCFunction_Type );
    const_tuple_str_plain_self_str_plain_text_str_plain_stream_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_text_str_plain_stream_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_text_str_plain_stream_tuple, 1, const_str_plain_text ); Py_INCREF( const_str_plain_text );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_text_str_plain_stream_tuple, 2, const_str_plain_stream ); Py_INCREF( const_str_plain_stream );
    const_tuple_str_plain_self_str_plain_before_str_plain_after_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_before_str_plain_after_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_before_str_plain_after_tuple, 1, const_str_plain_before ); Py_INCREF( const_str_plain_before );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_before_str_plain_after_tuple, 2, const_str_plain_after ); Py_INCREF( const_str_plain_after );
    const_tuple_str_plain_n_str_plain_start_symbol_str_plain_column0_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_str_plain_n_str_plain_start_symbol_str_plain_column0_tuple, 0, const_str_plain_n ); Py_INCREF( const_str_plain_n );
    PyTuple_SET_ITEM( const_tuple_str_plain_n_str_plain_start_symbol_str_plain_column0_tuple, 1, const_str_plain_start_symbol ); Py_INCREF( const_str_plain_start_symbol );
    PyTuple_SET_ITEM( const_tuple_str_plain_n_str_plain_start_symbol_str_plain_column0_tuple, 2, const_str_plain_column0 ); Py_INCREF( const_str_plain_column0 );
    const_tuple_str_digest_b9c4baf879ebd882d40843df3a4dead7_str_plain_x_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_digest_b9c4baf879ebd882d40843df3a4dead7_str_plain_x_tuple, 0, const_str_digest_b9c4baf879ebd882d40843df3a4dead7 ); Py_INCREF( const_str_digest_b9c4baf879ebd882d40843df3a4dead7 );
    PyTuple_SET_ITEM( const_tuple_str_digest_b9c4baf879ebd882d40843df3a4dead7_str_plain_x_tuple, 1, const_str_plain_x ); Py_INCREF( const_str_plain_x );

#if _NUITKA_EXE
    /* Set the "sys.executable" path to the original CPython executable. */
    PySys_SetObject(
        (char *)"executable",
        const_str_digest_58961c73026e70b23b08cf381b49e04e
    );
#endif
}

// In debug mode we can check that the constants were not tampered with in any
// given moment. We typically do it at program exit, but we can add extra calls
// for sanity.
#ifndef __NUITKA_NO_ASSERT__
void checkGlobalConstants( void )
{

}
#endif

void createGlobalConstants( void )
{
    if ( _sentinel_value == NULL )
    {
#if PYTHON_VERSION < 300
        _sentinel_value = PyCObject_FromVoidPtr( NULL, NULL );
#else
        // The NULL value is not allowed for a capsule, so use something else.
        _sentinel_value = PyCapsule_New( (void *)27, "sentinel", NULL );
#endif
        assert( _sentinel_value );

        _createGlobalConstants();
    }
}
